import { NextRequest, NextResponse } from 'next/server';
import { BoundedCache } from '../../../src/lib/bounded-cache';
import { abortStatus, fetchWithLimits } from '../../../src/lib/request-limits';
import { canonicalImageUrl, parseImageProxyUrl } from '../../../src/lib/media-url';

export const dynamic = 'force-dynamic';

const USER_AGENT =
  process.env.USER_AGENT ||
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 NeanderthalApp/1.0 (https://github.com/asiffisa/Neanderthal)';

// The system prompt asks the model to avoid these; a model is not a guarantee, so enforce it
// here too and skip the upstream round trip entirely.
const TRIVIAL_DISALLOWED_TERMS = new Set([
  // Geometric divisions & portions
  'slice', 'slices', 'portion', 'portions', 'piece', 'pieces', 'chunk', 'chunks',
  'part', 'parts', 'side', 'sides', 'surface', 'surfaces', 'layer', 'layers',
  'exterior', 'interior', 'amount', 'amounts', 'fraction', 'fractions',
  'zone', 'zones', 'area', 'areas', 'section', 'sections', 'segment', 'segments',
  // Intangible sensations
  'smell', 'smells', 'scent', 'scents', 'fragrance', 'fragrances', 'aroma', 'aromas',
  'flavor', 'flavors', 'taste', 'tastes', 'odor', 'odors',
  // Abstract metrics & dimensions
  'temperature', 'temperatures', 'degree', 'degrees', 'speed', 'speeds', 'velocity',
  'rate', 'rates', 'mass', 'volume', 'energy'
]);

// Stop-words and descriptive adjectives to strip when simplifying complex phrases
const STOP_WORDS = new Set([
  'the', 'a', 'an', 'and', 'or', 'of', 'in', 'on', 'at', 'to', 'for', 'with', 'by',
  'from', 'as', 'into', 'through', 'during', 'before', 'after', 'above', 'below',
  'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'do',
  'does', 'did', 'very', 'really', 'specialized', 'traditional', 'natural', 'brilliant',
  'neighboring', 'specific', 'dense', 'thin', 'thick', 'microscopic', 'macroscopic',
  'active', 'actively', 'underlying', 'remarkable',
  // Conversational modifiers and adjectives frequently generated by LLMs:
  'entire', 'whole', 'single', 'individual', 'nascent', 'resembling', 'typical', 'like',
  'various', 'certain', 'particular', 'simple', 'complex', 'small', 'large', 'tiny', 'huge',
  'inner', 'outer', 'internal', 'external', 'primary', 'secondary', 'overall', 'respective'
]);

const IRREGULAR_STEMS: Record<string, string> = {
  bacteria: 'bacteri', bacterium: 'bacteri', protozoa: 'protozo', protozoon: 'protozo',
  mitochondria: 'mitochondri', mitochondrion: 'mitochondri', cilia: 'cili', cilium: 'cili',
  flagella: 'flagell', flagellum: 'flagell', algae: 'alg', alga: 'alg', fungi: 'fung',
  fungus: 'fung', bacilli: 'bacill', bacillus: 'bacill', larvae: 'larv', larva: 'larv',
  nuclei: 'nucle', nucleus: 'nucle', criteria: 'criteri', criterion: 'criteri',
  phenomena: 'phenomen', phenomenon: 'phenomen', stimuli: 'stimul', stimulus: 'stimul',
};

/** Fold singular and plural to one key so "photons" still matches the article "Photon". */
function stemWord(word: string): string {
  if (!word || word.length <= 3) return word;
  const w = word.toLowerCase();
  if (IRREGULAR_STEMS[w]) return IRREGULAR_STEMS[w];
  if (w.endsWith('ies') && w.length > 4) return w.slice(0, -3) + 'y';
  if (w.endsWith('es') && w.length > 4 && !w.endsWith('sses')) return w.slice(0, -2);
  if (w.endsWith('s') && w.length > 3 && !w.endsWith('ss')) return w.slice(0, -1);
  return w;
}

// Blacklist of Wikipedia maintenance banners, stub markers, disambiguation badges, citation icons, and UI symbols
const MAINTENANCE_IMAGE_FILENAME =
  /\b(question_book|ambox|disambig|stub|padlock|portal|crystal_clear|nuvola|wiki_letter|commons-logo|wikimedia-logo|wikimedia_button|symbol_question|gnome|fairytale|red_pencile|edit-ltr|click_here|arrow|check_mark|cross_mark|no_free_image|missing_image|placeholder|replace_this_image|image_needed|citation_needed|unreferenced|mergefrom|mergeto|cleanup|lock_icon|protection_lock|dialog-warning|dialog-information|office-book|system-help)\b/i;

function isJunkOrMaintenanceImage(urlOrPath: string): boolean {
  if (!urlOrPath) return false;
  // Inspect only the filename / tail of the path to avoid falsely matching the domain (e.g. upload.wikimedia.org)
  const filename = urlOrPath.split('/').slice(-2).join('/').toLowerCase();
  return (
    /\.svg($|\/|\.)/i.test(filename) ||
    MAINTENANCE_IMAGE_FILENAME.test(filename) ||
    /\.(pdf|webm|ogv|mp4|mov|ogg|wav|mp3|flac)($|\/|\.)/i.test(filename)
  );
}

function cleanExtractText(raw: string): string {
  return raw
    .replace(/<[^>]*>/g, '')
    .replace(/&nbsp;/g, ' ')
    .replace(/&amp;/g, '&')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/\s+/g, ' ')
    .trim();
}

function cleanSearchQuery(query: string): string {
  return query
    .replace(/\b(portrait|photograph|photo|picture|image|illustration|diagram|stills|wallpaper)\b/gi, '')
    .replace(/\s+/g, ' ')
    .trim();
}

function simplifyQuery(query: string): string {
  const words = query
    .toLowerCase()
    .replace(/[-_/]/g, ' ')
    .replace(/[^\w\s]/g, '')
    .split(/\s+/)
    .filter((w) => w.length > 2 && !STOP_WORDS.has(w));
  return words.slice(0, 3).join(' ');
}

const cleanAlphanumeric = (s: string) => s.toLowerCase().replace(/[^\w]/g, '');

function isPersonBiography(extract?: string, title?: string): boolean {
  if (!extract) return false;
  const text = extract.slice(0, 350);
  const hasBirthOrDates = /\((?:born\b|\d{1,2}\s+[A-Za-z]+\s+\d{3,4}|\d{3,4}\s*[-–—]\s*(?:\d{3,4}|present)?|c\.\s*\d{3,4}|\bfl\.\s*\d{3,4})/i.test(text);
  const hasOccupation = /\b(?:is|was) an? (?:[A-Z][a-z]+(?:\s+[A-Z][a-z]+)?\s+)?(?:former\s+|professional\s+)?(?:wrestler|actor|actress|singer|musician|guitarist|bassist|drummer|vocalist|rapper|composer|songwriter|athlete|footballer|cricketer|baseball|basketball|golfer|boxer|tennis player|politician|serial killer|pornographic|model|influencer|comedian|celebrity|director|producer|playwright|poet|novelist)\b/i.test(text);
  return hasBirthOrDates || hasOccupation;
}

function isDisambiguationOrNameListPage(extract?: string, title?: string): boolean {
  if (title && /\s\((?:disambiguation|surname)\)$/i.test(title)) return true;
  if (!extract) return false;
  const text = extract.slice(0, 250).toLowerCase();
  return (
    text.includes('is both a surname and a given name') ||
    text.includes('is a surname') ||
    text.includes('is a given name') ||
    text.includes('may refer to:') ||
    text.includes('most commonly refers to:') ||
    text.includes('refer to:')
  );
}

function isEducationalOrScientificContext(context?: string): boolean {
  if (!context) return false;
  return /\b(onion|tear|plant|cell|biolog|botan|chemic|physic|space|geolog|earth|ocean|rock|mineral|quantum|molecul|enzyme|acid|tissue|bacteri|organism|neuroscience|acoustic|memor|brain|sound|scienc)/i.test(context);
}

function isMediaOrEntertainmentWork(extract?: string, title?: string): boolean {
  const t = (title || '').toLowerCase();
  const e = (extract || '').slice(0, 350).toLowerCase();
  if (/\b(album|soundtrack|extended play|single|song|band|video game|film|documentary|movie|series|franchise)\b/i.test(t)) {
    return true;
  }
  return /\b(?:is|was) an? (?:[0-9]{4}\s+)?(?:American|British|Canadian|Australian|French|German|Japanese|Chinese|Indian|[A-Z][a-z]+\s+)?(?:documentary|film|movie|album|song|single|rock band|punk band|punk rock band|musical group|music group|band|video game|television series|tv series)\b/i.test(e);
}

function generateCandidateSpellings(word: string): string[] {
  const w = word.toLowerCase().trim();
  if (w.length < 3 || w.length > 25 || w.includes(' ')) return [];

  const candidates = new Set<string>();

  // 1. Vowel doubling: in biochemistry and Latin taxonomy, vowels (especially i, o, e) are frequently doubled:
  // e.g. allin -> alliin, oocyte -> oocyte, zoology
  for (let i = 0; i < w.length; i++) {
    const char = w[i];
    if ('aeiou'.includes(char) && w[i - 1] !== char && w[i + 1] !== char) {
      const doubled = w.slice(0, i + 1) + char + w.slice(i + 1);
      candidates.add(doubled);
    }
  }

  // 2. Letter undoubling: e.g. alliin -> allin, chlorophyll -> chlorophyl
  for (let i = 0; i < w.length - 1; i++) {
    if (w[i] === w[i + 1]) {
      const undoubled = w.slice(0, i) + w.slice(i + 1);
      candidates.add(undoubled);
    }
  }

  // 3. Common biochemical / scientific suffixes
  if (w.endsWith('in') && !w.endsWith('iin')) {
    candidates.add(w.slice(0, -2) + 'iin'); // e.g. allin -> alliin
  }
  if (w.endsWith('ase') && !w.endsWith('iase')) {
    candidates.add(w.slice(0, -3) + 'iase'); // e.g. allinase -> alliinase
  }

  candidates.delete(w);
  return Array.from(candidates).slice(0, 6);
}

function isRelevantWikipediaPage(pageTitle: string, query: string, context?: string, extract?: string): boolean {
  if (!pageTitle || !query) return false;

  // Immediately reject disambiguation, surname directory, and index lists
  if (isDisambiguationOrNameListPage(extract, pageTitle)) {
    return false;
  }

  const alphaTitle = cleanAlphanumeric(pageTitle);
  const alphaQuery = cleanAlphanumeric(query);

  const normalize = (s: string) =>
    s
      .toLowerCase()
      .replace(/[-_/]/g, ' ')
      .replace(/[^\w\s]/g, '')
      .split(/\s+/)
      .filter((w) => !STOP_WORDS.has(w) && w.length > 2);

  const titleTokens = normalize(pageTitle);
  const queryTokens = normalize(query);
  const titleStems = titleTokens.map(stemWord);
  const queryStems = queryTokens.map(stemWord);
  const contextTokens = context ? normalize(context) : [];
  const lowerTitle = pageTitle.toLowerCase();
  const lowerExtract = (extract || '').toLowerCase();

  const isPerson = isPersonBiography(extract, pageTitle);
  const isMedia = isMediaOrEntertainmentWork(extract, pageTitle);
  const isScientific = isEducationalOrScientificContext(context);

  // If the page is a person biography:
  // Reject if:
  // 1. Context is scientific/educational
  // 2. Query is a single token that only matches a surname or first name (e.g. "allin" vs "Darby Allin"),
  //    unless the user explicitly typed the person's full name (alphaTitle === alphaQuery)
  if (isPerson) {
    if (isScientific) return false;
    if (queryTokens.length === 1 && alphaTitle !== alphaQuery) {
      return false;
    }
  }

  // If the page is a media work (film, album, song, band, game):
  // Reject if:
  // 1. Context is scientific/educational
  // 2. Query is a single token and title has multiple words (e.g. "allin" vs "Hated: GG Allin and the Murder Junkies")
  if (isMedia) {
    if (isScientific) return false;
    if (queryTokens.length === 1 && alphaTitle !== alphaQuery) {
      return false;
    }
  }

  // 1. Direct alphanumeric match (handles compound words like "Shock wave" vs "Shockwave", "deep sea" vs "deepsea")
  if (alphaTitle === alphaQuery) {
    return true;
  }

  // Singular/plural and stem matching (handles standard s/es and irregular Latin plurals like bacterium <-> bacteria)
  const stemTitle = stemWord(alphaTitle);
  const stemQuery = stemWord(alphaQuery);
  if (stemTitle === stemQuery) {
    return true;
  }

  // 2. Descriptive query containing the core entity:
  // e.g. query "actin-like cytoskeleton" contains title "Cytoskeleton",
  // or query "deep sea hydrothermal vent" contains title "Hydrothermal vent".
  // Every non-stopword token of the title is present in the query.
  if (
    titleTokens.length > 0 &&
    titleTokens.length <= queryTokens.length &&
    titleTokens.every((t, idx) => queryTokens.includes(t) || queryStems.includes(titleStems[idx]))
  ) {
    return true;
  }

  // 3. Multi-word query check: ensure at least 2 tokens match or >= 60% of tokens match
  if (queryTokens.length >= 2) {
    const matched = queryTokens.filter((q, i) => {
      const qStem = queryStems[i];
      return (
        titleTokens.includes(q) ||
        titleStems.includes(qStem) ||
        lowerTitle.includes(q) ||
        lowerExtract.includes(q) ||
        lowerExtract.includes(qStem)
      );
    }).length;
    if (matched >= 2 || matched / queryTokens.length >= 0.6) {
      return true;
    }
  }

  // 4. Single-token query check:
  // If query is a single token, only accept multi-word titles if:
  // - The page is NOT a person/biography (already checked above)
  // - The page is NOT a film/band/media title (already checked above)
  // - The title is concise (at most 2 content tokens, e.g. "Bacterial cell")
  // - The title contains the token or stem as a standalone word
  if (queryTokens.length === 1) {
    const q = queryTokens[0];
    const qStem = queryStems[0];
    if (titleTokens.length <= 2 && (titleTokens.includes(q) || titleStems.includes(qStem))) {
      return true;
    }
  }

  // 5. Token overlap check with context (if context is a concise entity)
  if (contextTokens.length > 0 && contextTokens.length <= 3) {
    const hasContextMatch = contextTokens.some((c) => titleTokens.includes(c) || lowerTitle.includes(c));
    const hasAnyQueryRel = queryTokens.some((q, i) =>
      titleTokens.includes(q) || titleStems.includes(queryStems[i]) || lowerTitle.includes(q) || lowerExtract.includes(q)
    );
    if (hasContextMatch && hasAnyQueryRel) return true;
  }

  return false;
}

function scoreWikipediaPage(page: any, query: string, context?: string): number {
  let score = 50 - (page.index ?? 10) * 4;

  const normTitle = cleanAlphanumeric(page.title || '');
  const normQ = cleanAlphanumeric(query);

  // Exact match bonus (e.g. "Shock wave" matching "shockwave")
  if (normTitle === normQ) {
    score += 75;
  } else if (normTitle.startsWith(normQ) || normTitle.endsWith(normQ)) {
    score += 25;
  } else if (normTitle.includes(normQ) || normQ.includes(normTitle)) {
    score += 15;
  }

  const title = (page.title || '').toLowerCase();
  const imgUrl = (page.thumbnail?.source || '').toLowerCase();

  // Disqualify vector logos, crests, SVGs, and Wikipedia template images
  if (isJunkOrMaintenanceImage(imgUrl)) {
    return -999;
  }

  // Disqualify disambiguation / surname pages
  if (isDisambiguationOrNameListPage(page.extract, page.title)) {
    return -999;
  }

  // Penalize or disqualify person biographies on general/scientific lookups
  if (isPersonBiography(page.extract, page.title)) {
    if (isEducationalOrScientificContext(context)) {
      return -999;
    }
    if (normTitle !== normQ) {
      score -= 50;
    }
  }

  // Wikipedia disambiguates a secondary sense with a parenthetical, e.g. "Shockwave (software)".
  // An unqualified query asked for the primary sense, so prefer the article without one.
  if (/\s\(.+\)$/.test(title) && !query.includes('(')) {
    score -= 45;
  }

  // Penalize logos and icons in encyclopedic lookups
  if (
    imgUrl.includes('logo') ||
    imgUrl.includes('icon') ||
    imgUrl.includes('crest') ||
    title.includes('logo')
  ) {
    score -= 40;
  }

  return score;
}

async function searchDuckDuckGoFast(
  parentSignal: AbortSignal,
  query: string,
  isExcluded: (url: string | null | undefined) => boolean,
  occurrence = 0
): Promise<{ title: string; imageUrl: string; sourceUrl: string } | null> {
  const signal = AbortSignal.any([parentSignal, AbortSignal.timeout(2000)]);

  try {
    const tokenUrl = `https://duckduckgo.com/?q=${encodeURIComponent(query)}&iax=images&ia=images`;
    const tokenRes = await fetchWithLimits(tokenUrl, {
      headers: {
        'User-Agent':
          'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36',
      },
      signal,
    });

    if (!tokenRes.ok) return null;
    const html = await tokenRes.text();
    const vqdMatch = html.match(/vqd=["']?([0-9-_]+)["']?/) || html.match(/vqd=([0-9-_]+)/);
    if (!vqdMatch) return null;

    const vqd = vqdMatch[1];
    const imgApiUrl = `https://duckduckgo.com/i.js?l=us-en&o=json&q=${encodeURIComponent(
      query
    )}&vqd=${vqd}&f=,,,&p=1`;

    const imgRes = await fetchWithLimits(imgApiUrl, {
      headers: {
        'User-Agent':
          'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36',
        Referer: 'https://duckduckgo.com/',
      },
      signal,
    });

    if (!imgRes.ok) return null;
    const imgData = await imgRes.json();
    const results = imgData.results || [];

    const valid = results.filter((r: any) => {
      const u = r.thumbnail || r.image;
      if (!u) return false;
      if (isExcluded(u)) return false;
      return true;
    });

    const chosen = valid[occurrence] || valid[0];
    if (chosen && (chosen.thumbnail || chosen.image)) {
      return {
        title: chosen.title || query,
        imageUrl: chosen.thumbnail || chosen.image,
        sourceUrl: chosen.url || `https://duckduckgo.com/?q=${encodeURIComponent(query)}`,
      };
    }
  } catch {
    // Timeout or network abort
  }
  return null;
}

async function getPageImagesFallback(
  signal: AbortSignal,
  pageTitle: string,
  isExcluded: (url: string | null | undefined) => boolean
): Promise<{ title: string; imageUrl: string; sourceUrl: string } | null> {
  const url = `https://en.wikipedia.org/w/api.php?action=query&titles=${encodeURIComponent(
    pageTitle
  )}&generator=images&gimlimit=12&prop=imageinfo&iiprop=url&iiurlwidth=600&format=json&origin=*`;

  try {
    const res = await fetchWithLimits(url, { headers: { 'User-Agent': USER_AGENT }, signal });
    if (!res.ok) return null;
    const data = await res.json();
    const pages = Object.values(data.query?.pages || {}) as any[];
    for (const p of pages) {
      const title = (p.title || '').toLowerCase();
      const info = p.imageinfo?.[0];
      const thumb = info?.thumburl || info?.url;
      if (!thumb || isExcluded(thumb)) continue;
      if (/\b(logo|icon|symbol|edit-ltr|commons-logo|duplicate|flag)\b/i.test(title)) continue;
      if (MAINTENANCE_IMAGE_FILENAME.test(title) || isJunkOrMaintenanceImage(thumb)) continue;
      if (/\.(pdf|webm|ogv|mp4|mov)$/i.test(title)) continue;
      return {
        title: pageTitle,
        imageUrl: thumb,
        sourceUrl: `https://en.wikipedia.org/wiki/${encodeURIComponent(pageTitle.replace(/\s+/g, '_'))}`,
      };
    }
  } catch {}
  return null;
}

async function searchWikipedia(
  signal: AbortSignal,
  searchTerm: string,
  occurrence: number,
  isExcluded: (url: string | null | undefined) => boolean,
  context?: string
): Promise<{ title: string; imageUrl: string; sourceUrl: string; extract?: string } | null> {
  const searchUrl = `https://en.wikipedia.org/w/api.php?action=query&generator=search&gsrsearch=${encodeURIComponent(
    searchTerm
  )}&gsrlimit=8&prop=pageimages|extracts&pithumbsize=600&pilimit=8&exintro=1&explaintext=1&redirects=1&format=json&origin=*`;

  try {
    const res = await fetchWithLimits(searchUrl, {
      headers: { 'User-Agent': USER_AGENT }, signal,
    });

    if (!res.ok) return null;
    const data = await res.json();
    const rawPages = (Object.values(data.query?.pages || {}) as any[]).sort(
      (a, b) => (a.index ?? 999) - (b.index ?? 999)
    );

    // 1. Check if an exact matching page exists (handles singular/plural e.g. "photons" -> "Photon", "bacterium" -> "Bacteria")
    const exactMatch = rawPages.find((p) => {
      const at = cleanAlphanumeric(p.title || '');
      const aq = cleanAlphanumeric(searchTerm);
      const st = stemWord(at);
      const sq = stemWord(aq);
      const matches = (
        at === aq ||
        st === sq ||
        (aq.endsWith('s') && !aq.endsWith('ss') && at === aq.slice(0, -1)) ||
        (at.endsWith('s') && !at.endsWith('ss') && at.slice(0, -1) === aq)
      );
      return matches && !isDisambiguationOrNameListPage(p.extract, p.title);
    });

    if (occurrence === 0 && exactMatch && exactMatch.thumbnail?.source && !isExcluded(exactMatch.thumbnail.source)) {
      return {
        title: exactMatch.title,
        imageUrl: exactMatch.thumbnail.source,
        sourceUrl: `https://en.wikipedia.org/wiki/${encodeURIComponent(exactMatch.title.replace(/\s+/g, '_'))}`,
        extract: exactMatch.extract,
      };
    }

    // 2. Score pages with thumbnails
    const validPages = rawPages.filter((p) => {
      const thumb = p.thumbnail?.source;
      return thumb && !isExcluded(thumb);
    });

    const scoredPages = validPages
      .filter((p) => isRelevantWikipediaPage(p.title || '', searchTerm, context, p.extract))
      .map((p) => ({ page: p, score: scoreWikipediaPage(p, searchTerm, context) }))
      .filter((item) => item.score > 0)
      .sort((a, b) => b.score - a.score);

    if (scoredPages.length > 0) {
      const targetPage = scoredPages[occurrence]?.page || scoredPages[0].page;
      if (targetPage && targetPage.thumbnail?.source) {
        const title = targetPage.title || searchTerm;
        return {
          title,
          imageUrl: targetPage.thumbnail.source,
          sourceUrl: `https://en.wikipedia.org/wiki/${encodeURIComponent(title.replace(/\s+/g, '_'))}`,
          extract: targetPage.extract,
        };
      }
    }

    // 3. Try candidate spellings for near-miss typos (e.g. vowel doubling in biochemistry/botany like "allin" -> "Alliin")
    // Runs before generic fallback scraping so a genuine canonical encyclopedic entity takes precedence
    const candidates = generateCandidateSpellings(searchTerm);
    if (candidates.length > 0) {
      const candidateUrl = `https://en.wikipedia.org/w/api.php?action=query&titles=${encodeURIComponent(
        candidates.join('|')
      )}&prop=pageimages|extracts&pithumbsize=600&pilimit=8&exintro=1&explaintext=1&redirects=1&format=json&origin=*`;
      try {
        const cRes = await fetchWithLimits(candidateUrl, {
          headers: { 'User-Agent': USER_AGENT }, signal,
        });
        if (cRes.ok) {
          const cData = await cRes.json();
          const cPages = (Object.values(cData.query?.pages || {}) as any[]).filter(
            (p) => p.pageid && p.pageid > 0 && !isDisambiguationOrNameListPage(p.extract, p.title)
          );
          for (const cand of candidates) {
            const match = cPages.find(
              (p) =>
                cleanAlphanumeric(p.title || '').toLowerCase() === cleanAlphanumeric(cand) &&
                !isPersonBiography(p.extract, p.title) &&
                !isMediaOrEntertainmentWork(p.extract, p.title)
            );
            if (match && match.thumbnail?.source && !isExcluded(match.thumbnail.source)) {
              return {
                title: match.title,
                imageUrl: match.thumbnail.source,
                sourceUrl: `https://en.wikipedia.org/wiki/${encodeURIComponent(match.title.replace(/\s+/g, '_'))}`,
                extract: match.extract,
              };
            }
          }
        }
      } catch {}
    }

    // 4. If exact matching page exists but lacked a lead infobox thumbnail (e.g. Photon), fetch images from that article
    if (exactMatch) {
      const fallback = await getPageImagesFallback(signal, exactMatch.title, isExcluded);
      if (fallback) {
        return {
          ...fallback,
          extract: exactMatch.extract,
        };
      }
    }

    // 5. If top relevant page lacked a lead thumbnail, fetch images from that article
    const topRelevant = rawPages.find((p) =>
      !isDisambiguationOrNameListPage(p.extract, p.title) &&
      isRelevantWikipediaPage(p.title || '', searchTerm, context, p.extract)
    );
    if (topRelevant && topRelevant !== exactMatch) {
      const fallback = await getPageImagesFallback(signal, topRelevant.title, isExcluded);
      if (fallback) {
        return {
          ...fallback,
          extract: topRelevant.extract,
        };
      }
    }
  } catch {
    // Network error
  }
  return null;
}

async function searchCommons(
  signal: AbortSignal,
  searchTerm: string,
  isExcluded: (url: string | null | undefined) => boolean,
  context?: string
): Promise<{ title: string; imageUrl: string; sourceUrl: string } | null> {
  const commonsUrl = `https://commons.wikimedia.org/w/api.php?action=query&generator=search&gsrsearch=${encodeURIComponent(
    searchTerm + ' -filetype:pdf -icon -filetype:webm -filetype:ogv -filetype:mp4'
  )}&gsrnamespace=6&gsrlimit=6&prop=imageinfo&iiprop=url&iiurlwidth=600&format=json&origin=*`;

  try {
    const res = await fetchWithLimits(commonsUrl, {
      headers: { 'User-Agent': USER_AGENT }, signal,
    });

    if (!res.ok) return null;
    const commonsData = await res.json();
    const cPages = Object.values(commonsData.query?.pages || {}) as any[];
    for (const cp of cPages) {
      const info = cp.imageinfo?.[0];
      const url = info?.thumburl || info?.url;
      const lower = (cp.title || '').toLowerCase();
      const rawTitle = (cp.title || '').replace(/^File:/i, '');

      if (
        !url ||
        isExcluded(url) ||
        /\.(pdf|webm|ogv|mp4|mov|ogg)$|\b(logo|icon|cocaine|smoking)\b/i.test(lower) ||
        MAINTENANCE_IMAGE_FILENAME.test(lower) ||
        isJunkOrMaintenanceImage(url)
      ) {
        continue;
      }

      // Check if image title is actually relevant to the topic
      if (!isRelevantWikipediaPage(rawTitle, searchTerm, context)) {
        continue;
      }

      return {
        title: rawTitle,
        imageUrl: url,
        sourceUrl: `https://commons.wikimedia.org/wiki/${encodeURIComponent((cp.title || searchTerm).replace(/\s+/g, '_'))}`,
      };
    }
  } catch {
    // Network error
  }
  return null;
}

interface ServerCacheEntry {
  data: {
    query: string;
    title: string;
    description: string;
    thumbnailUrl: string | null;
    fullImageUrl: string | null;
    sourceUrl: string;
    vendor: 'wikipedia' | 'duckduckgo';
    status: string;
  };
  timestamp: number;
}

const serverResolveCache = new BoundedCache<ServerCacheEntry['data']>(512, 4 * 1024 * 1024, 24 * 60 * 60 * 1000);
let activeResolutions = 0;

export async function GET(request: NextRequest) {
  const searchParams = request.nextUrl.searchParams;
  const query = searchParams.get('q');
  const context = searchParams.get('context')?.trim() || '';
  const requestedVendor =
    searchParams.get('source')?.toLowerCase() ||
    searchParams.get('vendor')?.toLowerCase() ||
    'auto';
  const excludedUrls = searchParams.getAll('exclude');
  const occurrence = Number(searchParams.get('occurrence') || '0');

  if (!query || !query.trim()) {
    return NextResponse.json({ error: 'Missing query parameter q' }, { status: 400 });
  }

  if (query.length > 300 || context.length > 300 || excludedUrls.length > 16 ||
      excludedUrls.some((url) => url.length > 4096) || request.url.length > 20000 ||
      !Number.isInteger(occurrence) || occurrence < 0 || occurrence > 50 ||
      !['auto', 'wikipedia', 'wiki', 'duckduckgo', 'ddg', 'web'].includes(requestedVendor)) {
    return NextResponse.json({ error: 'Invalid resolution parameters' }, { status: 400 });
  }
  const exclusions = new Set(excludedUrls.map(canonicalImageUrl));
  const cleanQuery = query.trim();
  const cacheKey = JSON.stringify([cleanQuery.toLowerCase(), context.toLowerCase(), requestedVendor, [...exclusions].sort(), occurrence]);

  // A generic shape, portion or sensation has no photograph; do not spend a request finding out.
  if (TRIVIAL_DISALLOWED_TERMS.has(cleanQuery.toLowerCase())) {
    return NextResponse.json({
      title: cleanQuery,
      description: 'Generic term.',
      thumbnailUrl: null,
      fullImageUrl: null,
      sourceUrl: '',
      status: 'not-found',
      vendor: 'wikipedia',
    }, { headers: { 'Cache-Control': 'public, s-maxage=86400' } });
  }

  // 1. Instant Cache Hit
  const cached = serverResolveCache.get(cacheKey);
  if (cached) {
    return NextResponse.json(cached, {
      headers: {
        'Cache-Control': 'public, s-maxage=86400, stale-while-revalidate=604800',
        'X-Cache': 'HIT',
      },
    });
  }

  if (activeResolutions >= 36) {
    return NextResponse.json({ error: 'Resolver is busy' }, { status: 503, headers: { 'Retry-After': '1' } });
  }
  activeResolutions++;
  const signal = AbortSignal.any([request.signal, AbortSignal.timeout(15000)]);
  try {
    let description = 'Public domain knowledge reference.';
    let resolvedTitle = cleanQuery;
    let resolvedSourceUrl = `https://en.wikipedia.org/w/index.php?search=${encodeURIComponent(
      cleanQuery
    )}&title=Special%3ASearch&fulltext=1`;
    let rawImageUrl: string | null = null;
    let resolvedVendor: 'wikipedia' | 'duckduckgo' = 'wikipedia';

    const isExcluded = (url: string | null | undefined): boolean => {
      const parsed = parseImageProxyUrl(url);
      if (!parsed) return true;
      if (isJunkOrMaintenanceImage(parsed.pathname)) return true;
      return exclusions.has(canonicalImageUrl(parsed.href));
    };

    // Clean filler words like "portrait photograph", "photo of", etc.
    const sanitizedQuery = cleanSearchQuery(cleanQuery) || cleanQuery;

    // Detect if this subject or overall topic is related to cinema, people, entertainment, or pop culture
    const combinedContext = `${sanitizedQuery} ${context}`.toLowerCase();
    const isCultureOrEntertainment =
      /\b(actor|actress|film|movie|cinema|director|singer|album|song|celebrity|wedding|stills|starring|tamil|telugu|malayalam|bollywood|hollywood|series|tv|show|character|husband|wife|marriage|sons|daughter|family)\b/i.test(
        combinedContext
      );

    // Context is ONLY valid if it is a concise entity (<= 3 words, no questions, not a paragraph)
    const isContextValid =
      context && !context.includes('?') && context.split(/\s+/).length <= 3;
    const hasContextInQuery =
      isContextValid && sanitizedQuery.toLowerCase().includes(context.toLowerCase());
    const wordsInQuery = sanitizedQuery.split(/\s+/).length;

    // Only enrich with context when dealing with pop culture / cinema where a short title is ambiguous (e.g. "Maya" -> "Maya Nayanthara")
    // For scientific, nature, and encyclopedic subjects, the entity name itself is the exact canonical title on Wikipedia!
    const shouldEnrichWithContext =
      isContextValid && !hasContextInQuery && isCultureOrEntertainment && wordsInQuery <= 2;
    const enrichedQuery = shouldEnrichWithContext
      ? `${sanitizedQuery} ${context}`.trim()
      : sanitizedQuery;

    // Determine vendor priority:
    // 1. If explicitly requested as DuckDuckGo -> DDG first
    // 2. If explicitly requested as Wikipedia -> Wikipedia first
    // 3. If 'auto':
    //    - If cinema/entertainment/people -> DuckDuckGo first! (Wikipedia excludes copyrighted stills/press photos)
    //    - Otherwise keep Wikipedia first, including alternative-image lookups.
    const wantsDuckDuckGo =
      requestedVendor === 'duckduckgo' ||
      requestedVendor === 'ddg' ||
      requestedVendor === 'web';
    const wantsWikipedia =
      requestedVendor === 'wikipedia' ||
      requestedVendor === 'wiki';

    const preferDDGFirst =
      wantsDuckDuckGo ||
      (!wantsWikipedia && isCultureOrEntertainment);

    // ROUTE A: Try DuckDuckGo First
    if (preferDDGFirst) {
      // Try with context-enriched query first, then base query
      let ddgResult = await searchDuckDuckGoFast(signal, enrichedQuery, isExcluded, occurrence);
      if (!ddgResult && enrichedQuery !== sanitizedQuery) {
        ddgResult = await searchDuckDuckGoFast(signal, sanitizedQuery, isExcluded, occurrence);
      }

      if (ddgResult) {
        rawImageUrl = ddgResult.imageUrl;
        resolvedTitle = ddgResult.title || cleanQuery;
        resolvedSourceUrl = ddgResult.sourceUrl;
        resolvedVendor = 'duckduckgo';
        description = `Live photography for "${cleanQuery}" via DuckDuckGo.`;
      }
    }

    // ROUTE B: Try Wikipedia First (or Fallback if DDG was empty)
    if (!rawImageUrl) {
      // 1. Try sanitized query FIRST (direct canonical Wikipedia entity name)
      let wikiResult = await searchWikipedia(signal,
        sanitizedQuery,
        occurrence,
        isExcluded,
        isContextValid ? context : undefined
      );

      // 2. If enriched query was constructed and base search had no lead thumbnail, try enriched query
      if (!wikiResult && enrichedQuery !== sanitizedQuery) {
        wikiResult = await searchWikipedia(signal,
          enrichedQuery,
          occurrence,
          isExcluded,
          isContextValid ? context : undefined
        );
      }

      if (wikiResult) {
        rawImageUrl = wikiResult.imageUrl;
        resolvedTitle = wikiResult.title;
        resolvedSourceUrl = wikiResult.sourceUrl;
        resolvedVendor = 'wikipedia';
        if (wikiResult.extract) {
          description = cleanExtractText(wikiResult.extract).slice(0, 240) + '...';
        }
      }
    }

    // ROUTE C: Wikimedia Commons (For scientific/diagrammatic subjects)
    if (!rawImageUrl) {
      let commonsResult = await searchCommons(signal, sanitizedQuery, isExcluded, isContextValid ? context : undefined);
      if (!commonsResult && enrichedQuery !== sanitizedQuery) {
        commonsResult = await searchCommons(signal, enrichedQuery, isExcluded, isContextValid ? context : undefined);
      }

      if (commonsResult) {
        rawImageUrl = commonsResult.imageUrl;
        resolvedTitle = commonsResult.title;
        resolvedSourceUrl = commonsResult.sourceUrl;
        resolvedVendor = 'wikipedia';
        description = `Scientific media archive illustration for "${cleanQuery}".`;
      }
    }


    // ROUTE D: Simplified Query (for long descriptive phrases)
    if (!rawImageUrl) {
      const simplified = simplifyQuery(sanitizedQuery);
      if (simplified && simplified.toLowerCase() !== sanitizedQuery.toLowerCase()) {
        const simpResult = await searchWikipedia(signal, simplified, 0, isExcluded);
        if (simpResult) {
          rawImageUrl = simpResult.imageUrl;
          resolvedTitle = simpResult.title;
          resolvedSourceUrl = simpResult.sourceUrl;
          resolvedVendor = 'wikipedia';
          if (simpResult.extract) {
            description = cleanExtractText(simpResult.extract).slice(0, 240) + '...';
          }
        }
      }
    }

    // ROUTE E: DuckDuckGo Final Fallback (if Wikipedia route was attempted first and found nothing)
    if (!rawImageUrl && !preferDDGFirst) {
      let ddgResult = await searchDuckDuckGoFast(signal, enrichedQuery, isExcluded, occurrence);
      if (!ddgResult && enrichedQuery !== sanitizedQuery) {
        ddgResult = await searchDuckDuckGoFast(signal, sanitizedQuery, isExcluded, occurrence);
      }

      if (ddgResult) {
        rawImageUrl = ddgResult.imageUrl;
        resolvedTitle = ddgResult.title || cleanQuery;
        resolvedSourceUrl = ddgResult.sourceUrl;
        resolvedVendor = 'duckduckgo';
        description = `Live visual result for "${cleanQuery}" via DuckDuckGo web search.`;
      }
    }

    if (rawImageUrl) {
      const thumbnailUrl = rawImageUrl.startsWith('http')
        ? `/api/media-proxy?url=${encodeURIComponent(rawImageUrl)}`
        : rawImageUrl;

      const payload = {
        query: cleanQuery,
        title: resolvedTitle,
        description,
        thumbnailUrl,
        fullImageUrl: thumbnailUrl,
        sourceUrl: resolvedSourceUrl,
        vendor: resolvedVendor,
        status: 'loaded',
      };

      serverResolveCache.set(cacheKey, payload, JSON.stringify(payload).length * 2);

      return NextResponse.json(payload, {
        headers: {
          'Cache-Control': 'public, s-maxage=86400, stale-while-revalidate=604800',
          'X-Cache': 'MISS',
        },
      });
    }

    signal.throwIfAborted();
    const notFoundPayload = {
      query: cleanQuery,
      title: resolvedTitle,
      description,
      thumbnailUrl: null,
      fullImageUrl: null,
      sourceUrl: resolvedSourceUrl,
      vendor: resolvedVendor,
      status: 'not-found' as const,
    };
    serverResolveCache.set(cacheKey, notFoundPayload as any, 256);
    return NextResponse.json(notFoundPayload);
  } catch (error) {
    return NextResponse.json({
      query: cleanQuery,
      status: 'not-found',
    }, { status: abortStatus(signal, request) });
  } finally {
    activeResolutions--;
  }
}
